### ISSUE TITLE
change babel options

### ISSUE THREAD

**Issue by Mouvedia** [locoslab/vue-typescript-jest#27]
Shouldn't you have a way to change the default babel options?
cf https://github.com/locoslab/vue-typescript-jest/blob/master/preprocessor.js#L4

**Comment by locobert** [comment]
Sorry for the long overdue reply. Official Jest support has been added to Vue.js and we do not use the approach of this repository anymore. We recommend to use the official TypeScript and Jest support and get started with [Vue CLI](https://cli.vuejs.org/).
